net.Receive("GBRP::bankreception", function()
    ply = LocalPlayer()
    local frame = vgui.Create("DFrame")
    frame:SetSize(1000,500)
    frame:Center()
    frame:MakePopup()
    frame:SetTitle("Banque")
    local withdrawButton = vgui.Create("DButton",frame)
    withdrawButton:SetText("Déposer de l'argent")
    withdrawButton:SetPos(100,100)
    withdrawButton:SetSize(350,200)
    withdrawButton.DoClick = function()
        local amount = ply:GetNWInt("GBRP::launderedmoney")
        if amount > 0 then
            net.Start("GBRP::bankdeposit")
            net.WriteUInt(amount,32)
            net.SendToServer()
            frame:Remove()
            ply:ChatPrint("Vous avez déposé " .. amount .. "$.")
            GAMEMODE:AddNotify("Vous avez déposé " .. amount .. "$.",0,2)
        else
            ply:ChatPrint("Solde insuffisant.")
            GAMEMODE:AddNotify("Solde insuffisant.",1,2)
        end
        frame:Remove()
    end
    local sellButton = vgui.Create("DButton",frame)
    sellButton:SetText("Retirer de l'argent")
    sellButton:SetPos(550,100)
    sellButton:SetSize(350,200)
    sellButton.DoClick = function()
        local textEntry = vgui.Create("DTextEntry",frame)
        textEntry:SetSize(200,25)
        textEntry:SetPlaceholderText("ex: 500")
        textEntry:Center()
        textEntry.OnEnter = function(self)
            local amount = tonumber(self:GetValue())
            if amount > 0 and ply:GetNWInt("GBRP::balance") - amount >= 0 then
                net.Start("GBRP::bankwithdraw")
                net.WriteUInt(amount,32)
                net.SendToServer()
                frame:Remove()
                ply:ChatPrint("Vous avez retiré " .. amount .. "$.")
                GAMEMODE:AddNotify("Vous avez retiré " .. amount .. "$.",0,2)
            elseif amount <= 0 then
                ply:ChatPrint("Valeur non valide.")
                GAMEMODE:AddNotify("Valeur non valide.",1,2)
            else
                ply:ChatPrint("Solde insuffisant.")
                GAMEMODE:AddNotify("Solde insuffisant.",1,2)
            end
        end
    end
    local balance = vgui.Create("DLabel",frame)
    balance:SetText("Solde: " .. tostring(ply:GetNWInt("GBRP::balance")) .. "$")
    balance:SetPos(100,400)
    balance:SetSize(200,25)
    local launderedmoney = vgui.Create("DLabel",frame)
    launderedmoney:SetText("Argent blanchis: " .. tostring(ply:GetNWInt("GBRP::launderedmoney")) .. "$")
    launderedmoney:SetPos(100,420)
    launderedmoney:SetSize(200,25)
end)

net.Receive("GBRP::shopreception", function()
    shop = ents.GetByIndex(net.ReadEntity())
    ply = LocalPlayer()
    if ply:IsGangChief() and shop:GetOwner() == ply:GetGang() then
        local frame = vgui.Create("DFrame")
        frame:SetSize(1000,500)
        frame:Center()
        frame:MakePopup()
        frame:SetTitle("Banque")
        local withdrawButton = vgui.Create("DButton",frame)
        withdrawButton:SetText("Retirer l'argent")
        withdrawButton:SetPos(100,100)
        withdrawButton:SetSize(350,200)
        withdrawButton.DoClick = function()
            net.Start("GBRP::shopwithdraw")
            net.WriteEntity(shop)
            net.SendToServer()
        end
        local sellButton = vgui.Create("DButton",frame)
        sellButton:SetText("Vendre le magasin")
        sellButton:SetPos(550,100)
        sellButton:SetSize(350,200)
        sellButton.DoClick = function()
            if ent:GetNWInt("owner") == ply:EntIndex() then
                net.Start("GBRP::sellshop")
                net.WriteEntity(shop)
                net.SendToServer()
            end
        end
        local priceLabel = vgui.Create("DLabel",frame)
        priceLabel:SetText("Prix: " .. ent.price .. "$")
        priceLabel:SetPos(100,400)
        priceLabel:SetSize(200,25)
        local balance = vgui.Create("DLabel",frame)
        balance:SetText("Solde: " .. tostring(ply:GetNWInt("GBRP::balance")) .. "$")
        balance:SetPos(100,420)
        balance:SetSize(200,25)
    end
end)