player_manager.AddValidModel("Families of Carson Avenue", "models/sentry/gtav/families/famcapm.mdl")
player_manager.AddValidModel("Families of Chamberlain Hills", "models/sentry/gtav/families/famfopm.mdl")
player_manager.AddValidModel("Families of Davis", "models/sentry/gtav/families/famdnpm.mdl")
player_manager.AddValidModel("Families Member(Female)", "models/sentry/gtav/families/famfpm.mdl")
player_manager.AddValidModel("Families Boss", "models/sentry/gtav/families/ogfampm.mdl")
player_manager.AddValidModel("Ballas of Original Covenant", "models/sentry/gtav/ballas/ballasorigpm.mdl")
player_manager.AddValidModel("Ballas of East Side", "models/sentry/gtav/ballas/ballaseastpm.mdl")
player_manager.AddValidModel("Ballas of South Side", "models/sentry/gtav/ballas/ballassoutpm.mdl")
player_manager.AddValidModel("Ballas Member(Female)", "models/sentry/gtav/ballas/balfpm.mdl")
player_manager.AddValidModel("Ballas Boss", "models/sentry/gtav/ballas/ogbalpm.mdl")
player_manager.AddValidModel("Female Lost Member White", "models/sentry/gtav/lost/lostgirlwpm.mdl")
player_manager.AddValidModel("Female Lost Member Black", "models/sentry/gtav/lost/lostgirlbpm.mdl")
player_manager.AddValidModel("Street Gangster", "models/sentry/gtav/families/stpunk2pm.mdl")
player_manager.AddValidModel("Soucent2", "models/sentry/gtav/families/soucent2pm.mdl")