player_manager.AddValidModel("Police Officer 1_1", "models/taggart/police01/male_01.mdl")
player_manager.AddValidHands("Police Officer 1_1", "models/weapons/taggart/c_arms_police01.mdl", 1, "0")
player_manager.AddValidModel("Police Officer 2_1", "models/taggart/police01/male_02.mdl")
player_manager.AddValidHands("Police Officer 2_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")
player_manager.AddValidModel("Police Officer 3_1", "models/taggart/police01/male_03.mdl")
player_manager.AddValidHands("Police Officer 3_1", "models/weapons/taggart/c_arms_police01.mdl", 1, "0")
player_manager.AddValidModel("Police Officer 4_1", "models/taggart/police01/male_04.mdl")
player_manager.AddValidHands("Police Officer 4_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")
player_manager.AddValidModel("Police Officer 5_1", "models/taggart/police01/male_05.mdl")
player_manager.AddValidHands("Police Officer 5_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")
player_manager.AddValidModel("Police Officer 6_1", "models/taggart/police01/male_06.mdl")
player_manager.AddValidHands("Police Officer 6_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")
player_manager.AddValidModel("Police Officer 7_1", "models/taggart/police01/male_07.mdl")
player_manager.AddValidHands("Police Officer 7_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")
player_manager.AddValidModel("Police Officer 8_1", "models/taggart/police01/male_08.mdl")
player_manager.AddValidHands("Police Officer 8_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")
player_manager.AddValidModel("Police Officer 9_1", "models/taggart/police01/male_09.mdl")
player_manager.AddValidHands("Police Officer 9_1", "models/weapons/taggart/c_arms_police01.mdl", 0, "0")